---
title: "Analise estatistica R"
author: "Maxwel Coura Oliveira"
date: "3/30/2021"
output: html_document
---


```{r}
library(tidyverse)
```


```{r}
library(RCurl)
# Baixando via GitHub
df_path <- getURL("https://raw.githubusercontent.com/maxwelco/workshop-esalq/main/data/residual.csv")

# Lendo via read_csv
residual <- read_csv(df_path)

residual
```


```{r}
residual1 <- residual %>% 
  mutate(control_prop = control / 100)

residual1
```


```{r}
residual2 <- residual1 %>% 
  mutate(control_prop = case_when(
    control_prop == 1.00 ~ 0.999,
    control_prop == 0.00 ~ 0.001,
    TRUE                 ~ control_prop
  ))

residual2
```


```{r}
residual3 <- residual2 %>%
  mutate_if(is_character, as_factor) %>% 
  mutate_at(c("year", "trt", "rep"), as_factor)

residual3
```


```{r}
ggplot(residual3, aes(x = herbicide, 
                      y = control_prop, color = year)) + 
  geom_point() +
  coord_flip() +
  ylim(0, 1)
```


```{r}
ggplot(residual3, aes(x = herbicide, 
                      y = control_prop, color = year)) + 
  geom_boxplot() + # veja que adicionei esse código para gerar o box plot
  geom_point() +
  coord_flip() +
  ylim(0, 1)
```


```{r}
library(car)
leveneTest(control_prop ~ year, data = residual3)
```

```{r}
library(glmmTMB)
modelo <- glmmTMB(control_prop ~ # variável resposta
                    herbicide * year + # variável fixa
                    (1|rep), # efeitos randomizados
                  family = beta_family(link = "logit"),
                  REML = FALSE,
                  data = residual3)
```


```{r}
glmmTMB:::Anova.glmmTMB(modelo)
```
Existe dif entre os trt (herbicidas) P < 0.01




--- Pos ANOVA


```{r}
library(emmeans)
```

```{r}
emmip(modelo, ~ herbicide | year, type="response") #+ coord_flip()
```


```{r}
lsmeans <- emmeans(modelo, # modelo
                   ~  herbicide * year, # efeito fixo
                   cont="pairwise", # tipo de comparação
                   type="response", # transforma os dados de volta ao original
                   alpha=0.05) # nivel 

lsmeans
```



```{r}
plot(lsmeans, # lsmeans
     ~ herbicide * year, # efeito fixo
     comparisons = TRUE, # quero comparar
     type="response", # transforma os dados de volta ao original
     alpha=0.05, # nivel
     adjust="none") # ajuste, pode ser Tukey por exemplo - None = Fisher LSD
```





